Vibing as a senior engineer.

=claude --dangerously-skip-permissions=

* Why

Vibe coding is always slop?

No need for real engineers any more?

learning is not necessary any more?


NO.

* context
elisp, not proficient, history: read, copy paste.

* The Timeline
** Brian storming (with chatGPT)
- docs/research.org
- docs/format.org

** Execution (with Claude Code)
- docs/commands.org
- project.org

** Findings
- first version of project.org looks scary in a glance. Instinctively ask it to do more home work.

  #+begin_quote
can you search for emacs built-in functions and/or functions provided by org-mode, see if any of the tasks don't needs to be done from scratch, we would like to rely on existing functionality as much as possible, e.g. since we are dealing with org-mode, I'd imaging some of the functions planed may already exist, so we don't have to reinvent the wheels. another big one is org-mode parsing, I don't think we need to do it ourselves? at least I remember reading about https://orgmode.org/worg/dev/org-element-api.html. also, we can use https://github.com/alphapapa/org-ql for quick querying etc..
  #+end_quote
